config/routes.rb
Rails.application.routes.draw do
  resources :empresas
  root 'home#index'

  resources :reclamos
  devise_for :users

end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :empresa
  belongs_to :user
end

app/models/reclamo.rb
class Reclamo < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
  before_action :set_empresa, only: [:show, :edit, :update, :destroy]

  # GET /empresas
  # GET /empresas.json
  def index
    @empresas = Empresa.all

    @empresa = Empresa.new

  end

  # GET /empresas/1
  # GET /empresas/1.json
  def show
  end

  # GET /empresas/new
  def new
    @empresa = Empresa.new
  end

  # GET /empresas/1/edit
  def edit
  end

  # POST /empresas
  # POST /empresas.json
  def create
    @empresa = Empresa.new(empresa_params)

    respond_to do |format|
      if @empresa.save
        format.html { redirect_to empresas_url, notice: 'Empresa was successfully created.' }
        format.json { render :show, status: :created, location: @empresa }
      else
        format.html { render :new }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empresas/1
  # PATCH/PUT /empresas/1.json
  def update
    respond_to do |format|
      if @empresa.update(empresa_params)
        format.html { redirect_to @empresa, notice: 'Empresa was successfully updated.' }
        format.json { render :show, status: :ok, location: @empresa }
      else
        format.html { render :edit }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empresas/1
  # DELETE /empresas/1.json
  def destroy
    @empresa.destroy
    respond_to do |format|
      format.html { redirect_to empresas_url, notice: 'Empresa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empresa
      @empresa = Empresa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def empresa_params
      params.require(:empresa).permit(:nombre, :telefono)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reclamos_controller.rb
class ReclamosController < ApplicationController
  before_action :set_reclamo, only: [:show, :edit, :update, :destroy]

  # GET /reclamos
  # GET /reclamos.json
  def index
    @reclamos = Reclamo.all
  end

  # GET /reclamos/1
  # GET /reclamos/1.json
  def show
  end

  # GET /reclamos/new
  def new
    @reclamo = Reclamo.new
  end

  # GET /reclamos/1/edit
  def edit
  end

  # POST /reclamos
  # POST /reclamos.json
  def create
    @reclamo = Reclamo.new(reclamo_params)

    respond_to do |format|
      if @reclamo.save
        format.html { redirect_to @reclamo, notice: 'Reclamo was successfully created.' }
        format.json { render :show, status: :created, location: @reclamo }
      else
        format.html { render :new }
        format.json { render json: @reclamo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reclamos/1
  # PATCH/PUT /reclamos/1.json
  def update
    respond_to do |format|
      if @reclamo.update(reclamo_params)
        format.html { redirect_to @reclamo, notice: 'Reclamo was successfully updated.' }
        format.json { render :show, status: :ok, location: @reclamo }
      else
        format.html { render :edit }
        format.json { render json: @reclamo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reclamos/1
  # DELETE /reclamos/1.json
  def destroy
    @reclamo.destroy
    respond_to do |format|
      format.html { redirect_to reclamos_url, notice: 'Reclamo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reclamo
      @reclamo = Reclamo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reclamo_params
      params.require(:reclamo).permit(:nombre_empresa, :reclamo, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
  :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reclamos_helper.rb
module ReclamosHelper
end

app/views/comunes/_display_partial_menu.html.erb
<ul class ="nav navbar-nav navbar-right">
  <% if user_signed_in? %>
    <li>
      <a href = "<%= destroy_user_session_path %>" data-method ="delete">
        Salir
      </a>
    </li>
  <% else %>
    <li>
      <a href ="<%= new_user_session_path %>">
        Login
      </a>
    </li>
    <li>
      <a href =" <%= new_user_registration_path %>">
        Registro
      </a>
    </li>
  <% end %>
</ul>

<nav class="navbar navbar-default navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <% if user_signed_in? %>
          <li class="active">
            <%= link_to "Consultar Usuario", empresas_path %>
          </li>
        <% else %>
          <li  class="active">

          </li>
        <% end %>



      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li>
          <p class="navbar-text">Hello <%= current_user.email %> <%= link_to "Sign out", destroy_user_session_path, :method => 'delete'%></p>
        </li>
        <% else %>
        <li>
          <p class="navbar-text">Already have an account?</p>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <b>Login</b>
            <span class="caret"></span>
          </a>
          <ul id="login-dp" class="dropdown-menu">
            <li>
               <div class="row">
                  <div class="col-md-12">
                    Login via
                    <div class="social-buttons">
                      <a href="#" class="btn btn-fb"><i class="fa fa-facebook"></i> Facebook</a>
                      <a href="#" class="btn btn-tw"><i class="fa fa-twitter"></i> Twitter</a>
                    </div>
                    or
                     <!-- acdc -->
                     <%= render :file => '/devise/sessions/new' %>
                     <!-- acdc -->
                  </div>
                  <div class="bottom text-center">
                    New here ? <a href="#"><b>Join Us</b></a>
                  </div>
               </div>
            </li>
          </ul>
        </li>
        <%end%>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/comunes/_table_row.html.erb
<tr>
  <td><%= empresa.nombre %></td>
  <td><%= empresa.telefono %></td>
  <td><%= link_to 'Show', empresa %></td>
  <td><%= link_to 'Edit', edit_empresa_path(empresa) %></td>
  <td><%= link_to 'Destroy', empresa, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, :class => 'delete_empresa' %></td>
</tr>

app/views/empresas/_form.html.erb
<% modal ||= false %>
<% remote = modal ? true : false %>
<%= form_for(@empresa, remote: remote, html:{role: :form, 'data-model' => 'empresa'}) do |f| %>
  <% if @empresa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@empresa.errors.count, "error") %> prohibited this empresa from being saved:</h2>

      <ul>
      <% @empresa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre, class: 'control-label' %><br>
    <%= f.text_field :nombre, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :telefono, class: 'control-label' %><br>
    <%= f.number_field :telefono, class: 'form-control' %>
    <span class="help-block"></span>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', class: 'btn btn-default' %>
  </div>
<% end %>

app/views/empresas/edit.html.erb
<h1>Editing Empresa</h1>

<%= render 'form' %>

<%= link_to 'Show', @empresa %> |
<%= link_to 'Back', empresas_path %>

app/views/empresas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Empresas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Telefono</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <br>

    <% @empresas.each do |empresa| %>
      <%= render partial: '/comunes/table_row', locals: {empresa: empresa} %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Empresa', '#new_person_modal', 'data-toggle' => 'modal'%>

<div class="modal fade" id="new_person_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Create new person</h4>
      </div>
      <div class="modal-body">
        <%# Render the new person form (passing modal => true to enable remote => true) %>
        <%= render 'form', modal: true %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/empresas/new.html.erb
<h1>New Empresa</h1>

<%= render 'form', empresa: @empresa %>

<%= link_to 'Back', empresas_path %>

app/views/empresas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @empresa.nombre %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @empresa.telefono %>
</p>
<%= link_to 'Edit', edit_empresa_path(@empresa) %> |
<%= link_to 'Back', empresas_path %>

app/views/home/index.html.erb
<% if user_signed_in? %>
  <h1>Selecciona Alguna Opcion del Menu</h1>
<% else %>
  <h1>Inicia Sesion Para Obtener Opciones</h1>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DesafioFinal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
		<%= render '/comunes/display_partial_menu' %>
<%= yield %>

</body>
</html>

app/views/reclamos/_form.html.erb
<%= form_for(@reclamo) do |f| %>
  <% if @reclamo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reclamo.errors.count, "error") %> prohibited this reclamo from being saved:</h2>

      <ul>
      <% @reclamo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre_empresa %><br>
    <%= f.text_field :nombre_empresa %>
  </div>
  <div class="field">
    <%= f.label :reclamo %><br>
    <%= f.text_field :reclamo %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reclamos/edit.html.erb
<h1>Editing Reclamo</h1>

<%= render 'form' %>

<%= link_to 'Show', @reclamo %> |
<%= link_to 'Back', reclamos_path %>

app/views/reclamos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reclamos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre empresa</th>
      <th>Reclamo</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reclamos.each do |reclamo| %>
      <tr>
        <td><%= reclamo.nombre_empresa %></td>
        <td><%= reclamo.reclamo %></td>
        <td><%= reclamo.user %></td>
        <td><%= link_to 'Show', reclamo %></td>
        <td><%= link_to 'Edit', edit_reclamo_path(reclamo) %></td>
        <td><%= link_to 'Destroy', reclamo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reclamo', new_reclamo_path %>

app/views/reclamos/new.html.erb
<h1>New Reclamo</h1>

<%= render 'form' %>

<%= link_to 'Back', reclamos_path %>

app/views/reclamos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre empresa:</strong>
  <%= @reclamo.nombre_empresa %>
</p>

<p>
  <strong>Reclamo:</strong>
  <%= @reclamo.reclamo %>
</p>

<p>
  <strong>User:</strong>
  <%= @reclamo.user %>
</p>

<%= link_to 'Edit', edit_reclamo_path(@reclamo) %> |
<%= link_to 'Back', reclamos_path %>